name: time-liner

on:
  push:
    branches:
      - master
    paths:
      - "packages/time-liner/**"
      - ".github/workflows/time-liner.yml"
  pull_request:
    paths:
      - "packages/time-liner/**"
      - ".github/workflows/time-liner.yml"
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/time-liner

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: "20.x"
          cache: yarn
          cache-dependency-path: packages/time-liner/yarn.lock
      - run: yarn install --frozen-lockfile --ignore-scripts
      - run: yarn lint
      - run: yarn compile
