version: '3'
services:
  app:
    container_name: "slack-app"
    build:
      dockerfile: packages/emoji-sommelier/Dockerfile
      context: ../..
      args:
        STAGE: dev
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
